"""Write .streamlit/secrets.toml from the configuration already stored locally.

Hosts without a persistent disk can't read data/copier.db or keep a Telegram
session file, so everything has to travel as secrets instead. This collects
what's already working locally and writes it to a gitignored file:

    ./.venv/bin/python tools/make_secrets.py

The Telegram session is exported from your existing login, so there's nothing
to re-authorise. Secrets are written to the file and never printed — the
summary shown is masked.

Paste the file's contents into Streamlit Cloud under
App -> Settings -> Secrets, or keep it for local testing.
"""

import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from telethon import TelegramClient  # noqa: E402
from telethon.sessions import StringSession  # noqa: E402

from copier import config, db  # noqa: E402

OUT_DIR = os.path.join(db.BASE_DIR, ".streamlit")
OUT_PATH = os.path.join(OUT_DIR, "secrets.toml")


def mask(value: str, keep: int = 4) -> str:
    if not value:
        return "(not set)"
    if len(value) <= keep * 2:
        return "*" * len(value)
    return "{}…{} ({} chars)".format(value[:keep], value[-keep:], len(value))


async def export_session(api_id: int, api_hash: str):
    """Re-key the existing on-disk login into a portable string."""
    disk_session = config.SESSION_PATH + ".session"
    if not os.path.exists(disk_session):
        return None, "no local session file — sign in on the Connections page first"

    client = TelegramClient(config.SESSION_PATH, api_id, api_hash)
    await client.connect()
    try:
        if not await client.is_user_authorized():
            return None, "the local session exists but is not signed in"
        me = await client.get_me()
        portable = StringSession()
        portable.set_dc(client.session.dc_id, client.session.server_address,
                        client.session.port)
        portable.auth_key = client.session.auth_key
        who = "{} (@{})".format((me.first_name or "").strip(),
                                me.username or "no username")
        return (portable.save(), who)
    finally:
        await client.disconnect()


def write_toml(values) -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    lines = [
        "# Generated by tools/make_secrets.py",
        "#",
        "# THESE ARE LIVE CREDENTIALS. This file is gitignored - keep it that way.",
        "# TG_SESSION_STRING grants full access to your Telegram account;",
        "# revoke it from Telegram -> Settings -> Devices if it ever leaks.",
        "",
    ]
    for key, value in values:
        lines.append('{} = "{}"'.format(key, value))
    lines.append("")

    with open(OUT_PATH, "w") as handle:
        handle.write("\n".join(lines))
    os.chmod(OUT_PATH, 0o600)


async def main() -> int:
    db.init()
    cfg = config.load()

    missing = [name for name, value in (
        ("Deriv token", cfg.deriv_token),
        ("Deriv app_id", cfg.deriv_app_id),
        ("Telegram api_id", cfg.tg_api_id),
        ("Telegram api_hash", cfg.tg_api_hash),
    ) if not value]
    if missing:
        print("Not configured yet: {}".format(", ".join(missing)))
        print("Finish setup on the Connections page first.")
        return 1

    session, who = await export_session(int(cfg.tg_api_id), cfg.tg_api_hash)
    if not session:
        print("Could not export the Telegram session: {}".format(who))
        return 1

    values = [
        ("DERIV_TOKEN", cfg.deriv_token),
        ("DERIV_APP_ID", cfg.deriv_app_id),
        ("DERIV_ACCOUNT_ID", cfg.deriv_account_id),
        ("TG_API_ID", cfg.tg_api_id),
        ("TG_API_HASH", cfg.tg_api_hash),
        ("TG_CHAT_ID", cfg.tg_chat_id),
        ("TG_CHAT_TITLE", cfg.tg_chat_title),
        ("TG_SESSION_STRING", session),
    ]
    write_toml(values)

    print("Wrote {} (mode 0600)".format(OUT_PATH))
    print("Telegram login exported for: {}".format(who))
    print()
    print("Contents (masked):")
    for key, value in values:
        shown = value if key in ("DERIV_APP_ID", "DERIV_ACCOUNT_ID",
                                 "TG_API_ID", "TG_CHAT_ID", "TG_CHAT_TITLE") \
            else mask(value)
        print("  {:<18} = {}".format(key, shown))
    print()
    print("Next: open the file, copy all of it, and paste into")
    print("Streamlit Cloud -> App -> Settings -> Secrets.")
    print()
    print("TG_SESSION_STRING is a login credential for your Telegram account.")
    print("Do not commit it, paste it in chat, or share it.")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
