"""Write .streamlit/secrets.toml for a remote deployment.

Hosts without a persistent disk can't read data/copier.db or keep a Telegram
session file, so everything has to travel as secrets instead.

    ./.venv/bin/python tools/make_secrets.py

IMPORTANT — the Telegram login here is a SEPARATE one, created fresh by this
script. It is not a copy of the login on this machine.

Telegram invalidates an authorization key that is used from two IP addresses
at once (AuthKeyDuplicatedError), killing BOTH copies. So the remote instance
needs its own login, and this script signs in again to create one. Both appear
independently under Telegram -> Settings -> Devices and either can be revoked
without affecting the other.

Settings other than the session are read from the local database, so configure
the app locally first.
"""

import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from telethon import TelegramClient  # noqa: E402
from telethon.sessions import StringSession  # noqa: E402

from copier import config, db  # noqa: E402

OUT_DIR = os.path.join(db.BASE_DIR, ".streamlit")
OUT_PATH = os.path.join(OUT_DIR, "secrets.toml")


def mask(value: str, keep: int = 4) -> str:
    if not value:
        return "(not set)"
    if len(value) <= keep * 2:
        return "*" * len(value)
    return "{}…{} ({} chars)".format(value[:keep], value[-keep:], len(value))


def write_toml(values) -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    lines = [
        "# Generated by tools/make_secrets.py",
        "#",
        "# THESE ARE LIVE CREDENTIALS. This file is gitignored - keep it that way.",
        "# TG_SESSION_STRING is a SEPARATE Telegram login for the remote host.",
        "# Do not also run it locally: one authorization key used from two IPs",
        "# is invalidated by Telegram and both copies stop working.",
        "# Revoke it any time from Telegram -> Settings -> Devices.",
        "",
    ]
    for key, value in values:
        lines.append('{} = "{}"'.format(key, value))
    lines.append("")
    with open(OUT_PATH, "w") as handle:
        handle.write("\n".join(lines))
    os.chmod(OUT_PATH, 0o600)


async def main() -> int:
    db.init()
    cfg = config.load()

    missing = [name for name, value in (
        ("Deriv token", cfg.deriv_token),
        ("Deriv app_id", cfg.deriv_app_id),
        ("Telegram api_id", cfg.tg_api_id),
        ("Telegram api_hash", cfg.tg_api_hash),
    ) if not value]
    if missing:
        print("Not configured yet: {}".format(", ".join(missing)))
        print("Finish setup on the Connections page first.")
        return 1

    print("=" * 68)
    print("This creates a SEPARATE Telegram login for the remote host.")
    print("It does not copy, move or disturb the login on this machine.")
    print()
    print("Telegram kills an authorization key used from two IPs at once, so")
    print("the remote copy must be its own login. You'll be asked for the")
    print("code Telegram sends you, exactly as when signing in here.")
    print("=" * 68)
    print()

    phone = cfg.tg_phone or input("Phone (+countrycode…): ").strip()

    client = TelegramClient(StringSession(), int(cfg.tg_api_id), cfg.tg_api_hash)
    try:
        await client.start(phone=lambda: phone)
        me = await client.get_me()
        session = client.session.save()
    finally:
        await client.disconnect()

    values = [
        ("DERIV_TOKEN", cfg.deriv_token),
        ("DERIV_APP_ID", cfg.deriv_app_id),
        ("DERIV_ACCOUNT_ID", cfg.deriv_account_id),
        ("MODE", cfg.mode),
        ("TG_API_ID", cfg.tg_api_id),
        ("TG_API_HASH", cfg.tg_api_hash),
        ("TG_CHAT_ID", cfg.tg_chat_id),
        ("TG_CHAT_TITLE", cfg.tg_chat_title),
        ("TG_SESSION_STRING", session),
    ]
    write_toml(values)

    print()
    print("Signed in as: {} (@{})".format(
        (me.first_name or "").strip(), me.username or "no username"))
    print("Wrote {} (mode 0600)".format(OUT_PATH))
    print()
    print("Contents (masked):")
    for key, value in values:
        shown = value if key in ("DERIV_APP_ID", "DERIV_ACCOUNT_ID", "MODE",
                                 "TG_API_ID", "TG_CHAT_ID", "TG_CHAT_TITLE") \
            else mask(value)
        print("  {:<18} = {}".format(key, shown))
    print()
    print("Next: paste the file into the host's secrets store.")
    print()
    print("Run the copier in ONE place at a time. Two instances sharing a")
    print("login will both be cut off by Telegram; two separate logins are")
    print("fine, but they would each copy the same signal twice.")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
